version: 2.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: LsohuXRLZ7rYIUlBx/sKRWggp6qzHWh2wge+DNrDJPnPoeQnNrKprYOBex6rpQ4f
before_build:
  - dotnet restore
build:
  project: .\Serilog.Sinks.AzureWebJobsTraceWriter.sln
  verbosity: minimal
after_build:
  - dotnet pack -o ../.. /p:PackageVersion=2.0.%appveyor_build_version% 
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
    - dotnet test tests\Serilog.Sinks.AzureWebJobsTraceWriter.UnitTests
   